# Generated by Django 5.0.2 on 2024-02-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenurdu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='notes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='qpaper',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='youtube_link',
            field=models.CharField(max_length=100),
        ),
    ]
