# Generated by Django 5.0.2 on 2024-02-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenurdu', '0002_alter_content_notes_alter_content_qpaper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
