# Generated by Django 5.0.2 on 2024-02-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenurdu', '0005_remove_subject_standard_notes_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
