# Generated by Django 5.0.2 on 2024-02-15 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_notes_qpaper_youtube_delete_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='standard',
        ),
        migrations.AddField(
            model_name='notes',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.standard'),
        ),
        migrations.AddField(
            model_name='qpaper',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.standard'),
        ),
        migrations.AddField(
            model_name='youtube',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.standard'),
        ),
    ]
