# Generated by Django 5.0.2 on 2024-02-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_youtube_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='qpaper',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
